<h3>Novo Usuario</h3>

<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'users','action'=>'new')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br><br>";
echo $this->formRow($form->get('email'))."<br><br>";
echo $this->formRow($form->get('password'))."<br><br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();




